# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"Embeddings": "01_goodness_of_monolingual_embeddings.ipynb",
         "Dictionary": "02_goodness_of_embeddings_across_languages.ipynb"}

modules = ["core.py"]

doc_url = "https://fastai.github.io/embedding_gym/"

git_url = "https://github.com/fastai/embedding_gym/tree/master/"

def custom_doc_links(name): return None
