# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {}

modules = []

doc_url = "https://fastai.github.io/embedding_gym/"

git_url = "https://github.com/fastai/embedding_gym/tree/master/"

def custom_doc_links(name): return None
